// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArB145yOEJFQuzLz_zIxR8ptTD6bBPpyA',
    appId: '1:314663216248:web:b7dd9a79782860708ff98d',
    messagingSenderId: '314663216248',
    projectId: 'app-de-encuestas',
    authDomain: 'app-de-encuestas.firebaseapp.com',
    storageBucket: 'app-de-encuestas.appspot.com',
    measurementId: 'G-VDBLHZMZH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9tYCgqojg5v-ipVAm0WVZ_KFsWDUcLgE',
    appId: '1:314663216248:android:c7e6874d133a47bc8ff98d',
    messagingSenderId: '314663216248',
    projectId: 'app-de-encuestas',
    storageBucket: 'app-de-encuestas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8n21bL8ldx1_Mb7gcUGleTlA9eJ0FlWQ',
    appId: '1:314663216248:ios:75bd3724118fab1d8ff98d',
    messagingSenderId: '314663216248',
    projectId: 'app-de-encuestas',
    storageBucket: 'app-de-encuestas.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8n21bL8ldx1_Mb7gcUGleTlA9eJ0FlWQ',
    appId: '1:314663216248:ios:6ed53c0810fd4bfb8ff98d',
    messagingSenderId: '314663216248',
    projectId: 'app-de-encuestas',
    storageBucket: 'app-de-encuestas.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
